networks:
  default:
  traefik:
    external: true

services:
  example:
    image: whoami
    restart: unless-stopped
    # ports:
    #   - 80:80 # Port of service
    volumes:
      # use generated folder for generated templates
      - ./generated/example:/example:ro # generated template "named example"
      # use volumes folder for data persistance
      - ./volumes/test:/test # volume "test" for service

    networks:
      - traefik # add to traefik network
      - default # add to default (stack internal) network
    